# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gotoaws < Formula
  desc "gotoaws is an interactive CLI tool that you can use to connect to your AWS resources (EC2, ECS container) using the AWS Systems Manager Session Manager"
  homepage "https://github.com/hupe1980/gotoaws"
  version "0.21.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hupe1980/gotoaws/releases/download/v0.21.0/gotoaws_Darwin_x86_64.tar.gz"
      sha256 "ce3af6048c619e4ac8846eeb420814c67daf60a4a3753daa2e7e2c3228f260dc"

      def install
        bin.install "gotoaws"
        bash_completion.install "completions/gotoaws.bash" => "gotoaws"
        zsh_completion.install "completions/gotoaws.zsh" => "_gotoaws"
        fish_completion.install "completions/gotoaws.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hupe1980/gotoaws/releases/download/v0.21.0/gotoaws_Darwin_arm64.tar.gz"
      sha256 "bef8f8de21e0f0937a853c57cfea380b5cdd798c2b9cd2a57259c64fee78ae2f"

      def install
        bin.install "gotoaws"
        bash_completion.install "completions/gotoaws.bash" => "gotoaws"
        zsh_completion.install "completions/gotoaws.zsh" => "_gotoaws"
        fish_completion.install "completions/gotoaws.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hupe1980/gotoaws/releases/download/v0.21.0/gotoaws_Linux_x86_64.tar.gz"
      sha256 "ff4ea3d963da44578a895fdb869dde593c4238433e9b2fa2de9771f8057a8b0a"

      def install
        bin.install "gotoaws"
        bash_completion.install "completions/gotoaws.bash" => "gotoaws"
        zsh_completion.install "completions/gotoaws.zsh" => "_gotoaws"
        fish_completion.install "completions/gotoaws.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hupe1980/gotoaws/releases/download/v0.21.0/gotoaws_Linux_arm64.tar.gz"
      sha256 "e8f21ba54a1e5753b6256df4f8d10d1f809fbc7dd36062e985c7fc53aaf1c7ac"

      def install
        bin.install "gotoaws"
        bash_completion.install "completions/gotoaws.bash" => "gotoaws"
        zsh_completion.install "completions/gotoaws.zsh" => "_gotoaws"
        fish_completion.install "completions/gotoaws.fish"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/hupe1980/gotoaws/releases/download/v0.21.0/gotoaws_Linux_armv6.tar.gz"
      sha256 "77fcc90ef18476c10c0dae684ff8946be325e0252f144b606f28ac38301b2035"

      def install
        bin.install "gotoaws"
        bash_completion.install "completions/gotoaws.bash" => "gotoaws"
        zsh_completion.install "completions/gotoaws.zsh" => "_gotoaws"
        fish_completion.install "completions/gotoaws.fish"
      end
    end
  end

  test do
    system "#{bin}/gotoaws -v"
  end
end
